### ISSUE TITLE
Do not consume the body twice

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylogs-container#10]
`ctx.body()` is an `InputStream` and should not be consumed twice:

https://github.com/whylabs/whylogs-container/blob/b8002e89423425c4b55ff24af101cf44d7890195/src/main/kotlin/ai/whylabs/services/whylogs/core/WhyLogsController.kt#L168

Reference: https://github.com/tipsy/javalin/issues/714

**Comment by naddeoa** [comment]
This was actually a side effect of request size exceeding request cache. It just showed up in a weird way, we weren't actually double parsing the body. At least not in a way that would cause issues until requests size were large enough.

We don't do any of that anymore. Now we just parse the body as a stream on the fly.

https://github.com/whylabs/whylogs-container/pull/11

The downside is that we can't print out the full request if we fail to parse it.

**Comment by naddeoa** [comment]
Change just got merged in.
